### ISSUE TITLE
[코멘트 요청]

### ISSUE THREAD

**Issue by daonez** [daonez/rabbitMarket_BE#19]
1. 사진업로드를 보통 어떻게 구현하는지 궁금합니다, 지금은  api로 따로 빼서  프론트가 이미지를 업로드한 시점에 백엔드가 img url을 주고 그것을 state에 저장했었습니다.
- 저희가 사진을 api로 따로 뺀 이유는  router.post 안에 또다시 router를 넣으면 안될것같아서였습니다. 조언부탁드립니다

**Comment by cleverleee** [comment]
사진업로드 기능을 multer 라이브러리를 사용해서 모듈화 시킨 점 확인했습니다. 
api 로 사진 기능을 따로 빼서 요청할수도 있지만, 보통은 multer 미들웨어화를 해서 사용합니다. 
multer 미들웨어를 등록하고,  multer함수 를 호출 하고 업로드 된 파일을 저장할 경로를 설정하시면됩니다. 
미들웨어에 등록해서 사진을 업로드 할때 업로드 제어 옵션이 있으니, 찾아보시면 사진 다중 업로드 할때도 도움이 되실것 같습니다.

**Comment by daonez** [comment]
> 사진업로드 기능을 multer 라이브러리를 사용해서 모듈화 시킨 점 확인했습니다. api 로 사진 기능을 따로 빼서 요청할수도 있지만, 보통은 multer 미들웨어화를 해서 사용합니다. multer 미들웨어를 등록하고, multer함수 를 호출 하고 업로드 된 파일을 저장할 경로를 설정하시면됩니다. 미들웨어에 등록해서 사진을 업로드 할때 업로드 제어 옵션이 있으니, 찾아보시면 사진 다중 업로드 할때도 도움이 되실것 같습니다.

감사합니다, 이번에도 이미지업로드 하는 일이 있는데 미들웨어로 해서 구현해보도록 하겠습니다
